[tool.isort]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"

[tool.black]
line-length = 88
target-version = ['py37', 'py38','py39']
include = '\.pyi?$'
exclude = '''
/(
    \ .direnv
    | \.eggs
    | \.git
    | \.venv
    | build
    | demo.py
)/
'''
preview = true